gfortran -O -o ave ave.o ../gklib/osx_kleylib ../lib/libccp4f_osx_intel.a ; strip ave
ld: warning: for symbol _prginf_ tentative definition of size 96 from ../gklib/osx_kleylib(gkquit.o) is is smaller than the real definition of size 84 from ../gklib/osx_kleylib(gkinit.o)
ld: warning: for symbol _coliar_ tentative definition of size 16 from ../gklib/osx_kleylib(gknarg.o) is being replaced by a real definition of size 4 from ../gklib/osx_kleylib(gkargs.o)
ld: warning: for symbol _prginf_ tentative definition of size 96 from ../gklib/osx_kleylib(stamp.o) is is smaller than the real definition of size 84 from ../gklib/osx_kleylib(gkinit.o)
ld: warning: for symbol _ccp4hdat_ tentative definition of size 512 from ../lib/libccp4f_osx_intel.a(ccp4h_summary_beg.o) is being replaced by a real definition of size 508 from ../lib/libccp4f_osx_intel.a(ccp4h_init_lib.o)
ld: warning: for symbol _ccp4hdat_ tentative definition of size 512 from ../lib/libccp4f_osx_intel.a(ccp4h_rule.o) is is smaller than the real definition of size 508 from ../lib/libccp4f_osx_intel.a(ccp4h_init_lib.o)
Undefined symbols:
  "_invert4matrix", referenced from:
      _invsym_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4spg_load_laue", referenced from:
      _inasu_ in libccp4f_osx_intel.a(csymlib_f.o)
      _inasu_ in libccp4f_osx_intel.a(csymlib_f.o)
      _setgrd_ in libccp4f_osx_intel.a(csymlib_f.o)
      _setgrd_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_MtzSetLookup", referenced from:
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidasx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidall_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzFree", referenced from:
      _MtzMemTidy in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrclos_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclos_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_utils_malloc", referenced from:
      _ccp4_FtoCString in libccp4f_osx_intel.a(library_f.o)
      _ccpfyp_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccpupc_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccplwc_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _pgdefn_ in libccp4f_osx_intel.a(csymlib_f.o)
      _asuset_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_ops_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_equal_ops_order_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_equal_ops_order_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_symops in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _epsln_ in libccp4f_osx_intel.a(csymlib_f.o)
      _centric_ in libccp4f_osx_intel.a(csymlib_f.o)
      _lkyin_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyout_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyset_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyset_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidasx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidasx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidall_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_set_datamode", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_read_row", referenced from:
      _mrdlin_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdlin_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_line_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_line_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_get_order", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4spg_get_multiplicity", referenced from:
      _epslon_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_epslon_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_lrbat", referenced from:
      _lrbat_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrbtit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrbscl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrbsetid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbscl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_seek_section", referenced from:
      _mposn_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_position_selection_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposnw_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_position_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_utils_idate", referenced from:
      _uidate_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_lrsymi", referenced from:
      _lrsymi_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_lrsymm", referenced from:
      _lrsymm_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_rotandtrn_to_symop", referenced from:
      _NumberToSymop in libccp4f_osx_intel.a(cmaplib_f.o)
  "__gfortran_copy_string", referenced from:
      _ccpdpn_ in libccp4f_osx_intel.a(ccpdpn.o)
      _ccpdpn_ in libccp4f_osx_intel.a(ccpdpn.o)
      _ccpdpn_ in libccp4f_osx_intel.a(ccpdpn.o)
      _ccpdpn_ in libccp4f_osx_intel.a(ccpdpn.o)
      _ccpdpn_ in libccp4f_osx_intel.a(ccpdpn.o)
      _ccpdpn_ in libccp4f_osx_intel.a(ccpdpn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ccpopn_ in libccp4f_osx_intel.a(ccpopn.o)
      _ubytes_ in libccp4f_osx_intel.a(ubytes.o)
      _ugerr_ in libccp4f_osx_intel.a(ugerr.o)
      _ccp4h_init_lib_ in libccp4f_osx_intel.a(ccp4h_init_lib.o)
      _ccp4h_init_lib_ in libccp4f_osx_intel.a(ccp4h_init_lib.o)
      _ccp4h_init_lib_ in libccp4f_osx_intel.a(ccp4h_init_lib.o)
      _ccp4h_init_lib_ in libccp4f_osx_intel.a(ccp4h_init_lib.o)
  "_ccp4_lwsymm", referenced from:
      _lwsymm_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzResLimits", referenced from:
      _lrrsol_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4spg_to_shortname", referenced from:
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_utils_hgetlimits", referenced from:
      _hgetlimits_ in libccp4f_osx_intel.a(library_f.o)
  "_ccp4_ismnf", referenced from:
      _mtz_check_for_mnf_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_utils_chmod", referenced from:
      _cchmod_ in libccp4f_osx_intel.a(library_f.o)
  "_ccp4_cmap_open", referenced from:
      _mwrhdl_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_open_header_by_name_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_open_header_by_id_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhds_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_check_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_set_local_header", referenced from:
      _ccp4_map_set_local_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_set_local_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_utils_print", referenced from:
      _outbuf_ in libccp4f_osx_intel.a(library_f.o)
      _cunlink_ in libccp4f_osx_intel.a(library_f.o)
      _ccpfyp_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_lwbsetid", referenced from:
      _lwbsetid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbsetidx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_write_section", referenced from:
      _mspew_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_all_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzAddHistory", referenced from:
      _lwhist_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwhstl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_get_grid", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4spg_print_recip_spgrp", referenced from:
      _asuset_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_ops_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_MtzNumActiveCol", referenced from:
      _lrinfo_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwrefl_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_mat4_to_symop", referenced from:
      _msywrt_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _symtr3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _symtr4_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_cmap_get_mapstats", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_lridx", referenced from:
      _lridx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lridc_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzInd2reso", referenced from:
      _sthlsq1_ in libccp4f_osx_intel.a(csymlib_f.o)
      _sts3r41_ in libccp4f_osx_intel.a(csymlib_f.o)
      _lstlsq1_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_write_section_header", referenced from:
      _ccp4_map_write_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzListInputColumn", referenced from:
      _lrclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrclid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_utils_time", referenced from:
      _utime_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _lwhstl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccpexists", referenced from:
      _ccpexs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4spg_print_recip_ops", referenced from:
      _prtrsm_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_spgrp_equal_order", referenced from:
      _ccp4spg_f_equal_ops_order_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4spg_put_in_asu", referenced from:
      _asuput_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_asuput_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4spg_is_sysabs", referenced from:
      _epslon_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_epslon_ in libccp4f_osx_intel.a(csymlib_f.o)
      _sysab_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_is_sysabs_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_cmap_set_cell", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzParseLabin", referenced from:
      _lkyin_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyout_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyset_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzMallocBatch", referenced from:
      _lbprt_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_set_origin", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_utils_mkdir", referenced from:
      _cmkdir_ in libccp4f_osx_intel.a(library_f.o)
  "_summary_output", referenced from:
      _ccp4h_init_clib_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_MtzNumSourceCol", referenced from:
      _lrncol_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrseek_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrrefl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidasx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_get_spacegroup", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_read_section_header", referenced from:
      _ccp4_map_read_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_utils_wrg", referenced from:
      _ccpwrg_ in libccp4f_osx_intel.a(library_f.o)
  "_MtzAssignHKLtoBase", referenced from:
      _lropen_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_banner", referenced from:
      _ccpvrs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccprcs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_cmap_set_mapstats", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclose_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_sum_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclosc_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_mean_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_lrbats", referenced from:
      _lrbats_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_set_symop", referenced from:
      _msywrt_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msyput_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_spgname_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msycpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_symmetry_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzPrintBatchHeader", referenced from:
      _lbprt_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_set_label", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
      _mttrep_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_replace_title_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mttcpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mttcpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_title_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_title_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_lhprt_adv", referenced from:
      _lhprt_adv_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4ProgramTime", referenced from:
      _getelapsed_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_cmap_get_dim", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_utils_setenv", referenced from:
      _ustenv_ in libccp4f_osx_intel.a(library_f.o)
  "_ccp4_file_seek", referenced from:
      _lrseek_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrrewd_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "__gfortran_line", referenced from:
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccpopn.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccpnun.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_init.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ugerr.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_pre_beg.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_summary_end.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_summary_beg.o)
      __gfortran_line$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_rule.o)
  "_ccp4_prog_vers", referenced from:
      _ccp4_prog_version_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccp4_prog_version_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_MtzOpenForWrite", referenced from:
      _lwopen_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzGet", referenced from:
      _lropen_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_utils_noinpbuf", referenced from:
      _ccpfyp_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_strtolower", referenced from:
      _ccplwc_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4spg_is_centric", referenced from:
      _centr_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_is_centric_ in libccp4f_osx_intel.a(csymlib_f.o)
      _centphase_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_centphase_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_signal", referenced from:
      _NumberToSymop in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrhdl_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrhdl_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_open_header_by_name_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_open_header_by_name_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_open_header_by_id_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_open_header_by_id_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhds_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhds_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhds_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_check_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_check_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_check_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwclose_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_auto_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclose_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_sum_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclosc_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_mean_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrclos_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_close_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msywrt_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msymop_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msymop_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msyput_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_spgname_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mspew_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mspew_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_all_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_all_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulp_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulp_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_section_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_section_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrsec_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mwrsec_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_part_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_part_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdlin_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdlin_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_line_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_line_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposn_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposn_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_position_selection_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_position_selection_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposnw_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposnw_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_position_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_position_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msycpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_symmetry_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_set_local_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_get_local_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _modecv_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_mode_to_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzNbat", referenced from:
      _lwbsetid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbsetidx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4spg_name_equal_to_lib", referenced from:
      _patsgp_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_cmap_get_symop", referenced from:
      _msymop_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msycpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_symmetry_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_get_mask", referenced from:
      _mskget_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_closemode", referenced from:
      _mclose_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_sum_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclosc_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_mean_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_get_label", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
      _HeaderPrint in libccp4f_osx_intel.a(cmaplib_f.o)
      _mttcpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_title_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_parse_start", referenced from:
      _symfr_driver in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_utils_isnan", referenced from:
      _qisnan_ in libccp4f_osx_intel.a(library_f.o)
      _set_magic_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _reset_magic_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _reset_magic_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4printf", referenced from:
      _qprint_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_lrcell", referenced from:
      _lrcell_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_lwbat", referenced from:
      _lwbat_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbtit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbscl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzNcol", referenced from:
      _lwidall_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidall_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_set_fft_grid", referenced from:
      _setgrd_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4spg_load_by_ccp4_num", referenced from:
      _NumberToSymop in libccp4f_osx_intel.a(cmaplib_f.o)
      _asuset_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_ccp4_num in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _setlim_ in libccp4f_osx_intel.a(csymlib_f.o)
      _setlim_zero_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_licence_exists", referenced from:
      _ccplic_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccperror", referenced from:
      _mrdhds_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_check_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrdhdr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_open_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccpfyp_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccperr_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _symfr2_ in libccp4f_osx_intel.a(csymlib_f.o)
      _pgdefn_ in libccp4f_osx_intel.a(csymlib_f.o)
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
      _asuset_ in libccp4f_osx_intel.a(csymlib_f.o)
      _asusym_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_ops_ in libccp4f_osx_intel.a(csymlib_f.o)
      _inasu_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_ccp4_num in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_symops in libccp4f_osx_intel.a(csymlib_f.o)
      _epslon_ in libccp4f_osx_intel.a(csymlib_f.o)
      _centr_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_is_centric_ in libccp4f_osx_intel.a(csymlib_f.o)
      _setgrd_ in libccp4f_osx_intel.a(csymlib_f.o)
      _lkyin_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyout_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lkyset_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lrassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwopen_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwopen_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwsymm_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbat_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbtit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbscl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwrefl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclos_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4spg_pgname_equal", referenced from:
      _pgnlau_ in libccp4f_osx_intel.a(csymlib_f.o)
      _patsgp_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_utils_realloc", referenced from:
      _ccpexs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_html_log_output", referenced from:
      _ccp4h_init_clib_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_errno", referenced from:
      _ccp4_errno$non_lazy_ptr in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4spg_generate_origins", referenced from:
      _calc_orig_ps_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_lhprt", referenced from:
      _lropen_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lhprt_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclos_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_lrassn", referenced from:
      _lrassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_fatal", referenced from:
      _ustenv_ in libccp4f_osx_intel.a(library_f.o)
      _ccpal1_ in libccp4f_osx_intel.a(library_f.o)
  "_ccp4_lwassn", referenced from:
      _lwassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzPut", referenced from:
      _lwclos_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4spg_name_de_colon", referenced from:
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_lwidx", referenced from:
      _lwid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidc_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwcell_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_number_label", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
      _HeaderPrint in libccp4f_osx_intel.a(cmaplib_f.o)
      _HeaderPrint in libccp4f_osx_intel.a(cmaplib_f.o)
      _mttcpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_title_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_parse", referenced from:
      _symfr_driver in libccp4f_osx_intel.a(csymlib_f.o)
  "_MtzArrayToBatch", referenced from:
      _lbprt_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "__gfortran_ioparm", referenced from:
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccpopn.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccpnun.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_init.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ugerr.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_pre_beg.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_summary_end.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_summary_beg.o)
      __gfortran_ioparm$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_rule.o)
  "_ccp4spg_centric_phase", referenced from:
      _centphase_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_centphase_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_MtzFreeBatch", referenced from:
      _lbprt_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbat_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwbtit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_lrreff", referenced from:
      _lrreff_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_lrrefl", referenced from:
      _lrrefl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzAssignColumn", referenced from:
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidas_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidasx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidasx_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidall_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwidall_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4spg_check_symm_cell", referenced from:
      _lwsymm_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_symop_to_mat4", referenced from:
      _symfr_driver in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_cmap_get_cell", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4spg_print_epsilon_zones", referenced from:
      _epsln_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4RCSDate", referenced from:
      _ccprcs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4spg_free", referenced from:
      _NumberToSymop in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4spg_mem_tidy in libccp4f_osx_intel.a(csymlib_f.o)
      _pgdefn_ in libccp4f_osx_intel.a(csymlib_f.o)
      _asuset_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_name_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_ops_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_ccp4_num in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_symops in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_file_length", referenced from:
      _ioArrayPrint in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_lwrefl", referenced from:
      _lwrefl_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzNref", referenced from:
      _lrinfo_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4spg_generate_indices", referenced from:
      _asuget_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_utils_outbuf", referenced from:
      _outbuf_ in libccp4f_osx_intel.a(library_f.o)
  "_MtzHklcoeffs", referenced from:
      _setrsl_ in libccp4f_osx_intel.a(csymlib_f.o)
      _lropen_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lstrsl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwcell_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwcell_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_get_origin", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposn_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_position_selection_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mposnw_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_position_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_seek_symop", referenced from:
      _msymop_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msycpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_symmetry_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_parse_delimiters", referenced from:
      _symfr_driver in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4ProgramName", referenced from:
      _ccpvrs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccprcs_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccppnm_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _lwhstl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwhstl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4fyp", referenced from:
      _ccpfyp_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_cmap_set_grid", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_num_symop", referenced from:
      _msymop_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_symm_matrix_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _msycpy_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_copy_symmetry_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4spg_print_centric_zones", referenced from:
      _centric_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_cmap_close", referenced from:
      _mwclose_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_auto_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclose_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_sum_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mclosc_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_close_user_mean_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mrclos_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_close_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_utils_translate_mode_float", referenced from:
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _modecv_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_mode_to_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzColLookup", referenced from:
      _lrassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_file_itemsize", referenced from:
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_get_grid_sample", referenced from:
      _fndsmp_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_utils_date", referenced from:
      _ccpdat_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _lwhstl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwhstl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_write_data", referenced from:
      _mwrsec_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_part_section_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_get_local_header", referenced from:
      _ccp4_map_get_local_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_get_local_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_cmap_read_section", referenced from:
      _mgulp_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulp_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_section_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_section_as_mode_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_section_header_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_file_is_read", referenced from:
      _ioArrayPrint in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_parse_end", referenced from:
      _symfr_driver in libccp4f_osx_intel.a(csymlib_f.o)
      _symfr_driver in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_utils_etime", referenced from:
      _ccptim_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ccptim_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ucputm_ in libccp4f_osx_intel.a(ccp4_general_f.o)
      _ucputm_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4_utils_flength", referenced from:
      _ccp4_FtoCString in libccp4f_osx_intel.a(library_f.o)
  "_ccp4_cmap_set_dim", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_MtzSetSortOrder", referenced from:
      _lwsort_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwsort_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwassn_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _lwclab_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_spgrp_reverse_lookup", referenced from:
      _pgdefn_ in libccp4f_osx_intel.a(csymlib_f.o)
      _asuset_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_ops_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_register_by_symops in libccp4f_osx_intel.a(csymlib_f.o)
      _epsln_ in libccp4f_osx_intel.a(csymlib_f.o)
      _centric_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_MtzXtalLookup", referenced from:
      _lwid_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_MtzMalloc", referenced from:
      _lwopen_noexit_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_get_datamode", referenced from:
      _HeaderReturn in libccp4f_osx_intel.a(cmaplib_f.o)
      _mgulpr_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_read_whole_sect_as_real_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_file_name", referenced from:
      _ioArrayPrint in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_lrtitl", referenced from:
      _lrtitl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_cmap_set_spacegroup", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4spg_load_by_ccp4_spgname", referenced from:
      _patsgp_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_load_by_name_ in libccp4f_osx_intel.a(csymlib_f.o)
      _msymlb3_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_lrsort", referenced from:
      _lrsort_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_symop_code", referenced from:
      _pgdefn_ in libccp4f_osx_intel.a(csymlib_f.o)
      _pgdefn_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_lwtitl", referenced from:
      _lwtitl_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_lrhist", referenced from:
      _lrhist_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_utils_bml", referenced from:
      _ccpbml_ in libccp4f_osx_intel.a(library_f.o)
  "_ccp4spg_is_in_pm_asu", referenced from:
      _inasu_ in libccp4f_osx_intel.a(csymlib_f.o)
      _ccp4spg_f_inasu_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4spg_is_in_asu", referenced from:
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
      _hklrange_ in libccp4f_osx_intel.a(csymlib_f.o)
  "_ccp4_cmap_set_order", referenced from:
      _HeaderInit in libccp4f_osx_intel.a(cmaplib_f.o)
  "_ccp4_nan", referenced from:
      _qnan_ in libccp4f_osx_intel.a(library_f.o)
      _equal_magic_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _set_magic_ in libccp4f_osx_intel.a(cmtzlib_f.o)
      _reset_magic_ in libccp4f_osx_intel.a(cmtzlib_f.o)
  "_ccp4_strerror", referenced from:
      _ccpfyp_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "__gfortran_filename", referenced from:
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccpopn.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccpnun.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_init.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ugerr.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_pre_beg.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_summary_end.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_summary_beg.o)
      __gfortran_filename$non_lazy_ptr in libccp4f_osx_intel.a(ccp4h_rule.o)
  "_ccp4_cmap_set_mask", referenced from:
      _mskput_ in libccp4f_osx_intel.a(cmaplib_f.o)
      _ccp4_map_write_skew_info_ in libccp4f_osx_intel.a(cmaplib_f.o)
  "_strtoupper", referenced from:
      _ccpupc_ in libccp4f_osx_intel.a(ccp4_general_f.o)
  "_ccp4spg_phase_shift", referenced from:
      _asuphp_ in libccp4f_osx_intel.a(csymlib_f.o)
ld: symbol(s) not found
collect2: ld returned 1 exit status
strip: can't open file: ave (No such file or directory)
make: *** [ave] Error 1
